jobs:
  experiment:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cleanup any existing .NET SDK installations
      - name: Clean existing .NET SDKs
        run: |
          rm -rf /usr/local/share/dotnet
          rm -rf /Users/runner/.dotnet

      - name: Check current .NET info
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET SDK 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Check .NET info after setup
        run: |
          dotnet --info || true
          which dotnet || true

