name: Check and Install .NET SDK

on: [push, pull_request]

jobs:
  check-and-install-sdk:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check existing .NET SDKs before installation
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Use pre-installed .NET SDK if available
        id: use-preinstalled-dotnet
        run: |
          if dotnet --list-sdks | grep -q '^6.0\.'; then
            echo "Using pre-installed .NET SDK 6.0"
            echo "::set-output name=skip_install::true"
          else
            echo "Pre-installed .NET SDK 6.0 not found"
            echo "::set-output name=skip_install::false"
          fi

      - name: Install .NET SDK
        if: steps.use-preinstalled-dotnet.outputs.skip_install == 'false'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Check existing .NET SDKs after installation
        run: |
          dotnet --info || true
          which dotnet || true
