name: .NET Setup on macOS and Ubuntu

on: 
  [push, pull_request]

jobs:
  macos-experiment:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current .NET info on macOS
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET SDK on macOS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Check .NET info after setup on macOS
        run: |
          dotnet --info || true
          which dotnet || true

  ubuntu-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current .NET info on Ubuntu
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET SDK on Ubuntu
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Check .NET info after setup on Ubuntu
        run: |
          dotnet --info || true
          which dotnet || true
