name: .NET Setup on macOS and Ubuntu

on: 
  [push, pull_request]

jobs:
  macos-experiment:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check current .NET info on macOS
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET SDK on macOS using dotnet-version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Specify the desired .NET SDK version here
          cache: false  # Disable caching

      - name: Check .NET info after setup on macOS
        run: |
          dotnet --info || true
          which dotnet || true
