name: .NET Setup on Multiple OS

on: [push, pull_request]

jobs:
  experiment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current .NET info
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Clear .NET SDK cache
        run: |
          if [[ $RUNNER_OS == 'macOS' ]]; then
            rm -rf /Users/runner/.dotnet
          elif [[ $RUNNER_OS == 'Linux' ]]; then
            rm -rf /usr/lib/dotnet
          elif [[ $RUNNER_OS == 'Windows' ]]; then
            Remove-Item -Recurse -Force C:\Program Files\dotnet
          fi
        shell: bash

      - name: Check .NET info after setup
        run: |
          dotnet --info || true
          which dotnet || true
