name: .NET Setup on macOS and Ubuntu

on: 
  [push, pull_request]

jobs:
  macos-experiment:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set custom install directory for .NET SDK
        run: |
          # Set the custom SDK install path
          export DOTNET_INSTALL_DIR="/Users/runner/.dotnet/custom_sdk_path"
          echo "Custom SDK path: $DOTNET_INSTALL_DIR"
        env:
          DOTNET_INSTALL_DIR: "/Users/runner/.dotnet/custom_sdk_path"

      - name: Check current .NET info on macOS (root path)
        run: |
          echo "Checking .NET version from root install path..."
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET SDK on macOS using dotnet-version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Specify the desired .NET SDK version here
          # cache: true
        env:
          DOTNET_INSTALL_DIR: ${{ env.DOTNET_INSTALL_DIR }}  # Pass the custom install directory

      - name: Check .NET info from the custom SDK path
        run: |
          echo "Checking .NET SDK installed at the custom path: $DOTNET_INSTALL_DIR"
          
          # Temporarily add the custom SDK path to PATH
          export PATH=$DOTNET_INSTALL_DIR:$PATH
          
          # Verify the .NET version and installation from the custom SDK path
          dotnet --info || true  # This will check the installed .NET version
          echo "Checking which dotnet executable is being used from custom SDK path..."
          which dotnet || true  # This will show where the dotnet executable is located
