name: .NET Setup on macOS and Ubuntu

on: 
  [push, pull_request]

jobs:
  experiment:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current .NET info
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Set up .NET SDK 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      # Set the DOTNET_ROOT to point to the .NET SDK location
      - name: Set DOTNET_ROOT
        run: |
          export DOTNET_ROOT=/Users/runner/.dotnet
          echo "DOTNET_ROOT is set to $DOTNET_ROOT"

      - name: Check .NET info after setup
        run: |
          dotnet --info || true
          which dotnet || true

