name: .NET Setup on Multiple OS

on: [push, pull_request]

jobs:
  experiment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-14, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current .NET info
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Create global.json to specify SDK version
        run: |
          echo '{ "sdk": { "version": "6.0.x" } }' > global.json

      - name: Uninstall default .NET SDKs on macOS
        if: matrix.os == 'macos-14' || matrix.os == 'macos-latest'
        run: |
          echo "Removing unwanted .NET SDK versions"
          sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.NETCore.App/8.*
          sudo rm -rf /usr/local/share/dotnet/sdk/8.*

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Ensure .NET SDK is in PATH
        run: |
          echo "Ensuring .NET SDK is in PATH"
          echo "/usr/local/share/dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Check .NET info after setup
        run: |
          dotnet --info || true
          which dotnet || true
