name: Check and Install .NET SDK

on: [push, pull_request]

jobs:
  check-and-install-sdk:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check existing .NET SDKs before installation
        run: |
          dotnet --info || true
          which dotnet || true

      - name: Clean existing .NET SDKs on Ubuntu or macOS
        if: runner.os != 'Windows'
        run: |
          rm -rf /usr/local/share/dotnet
          rm -rf ~/.dotnet

      - name: Clean existing .NET SDKs on Windows
        if: runner.os == 'Windows'
        run: |
          Remove-Item -Recurse -Force "C:\Program Files\dotnet"
          Remove-Item -Recurse -Force "$env:USERPROFILE\.dotnet"

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Check existing .NET SDKs after installation
        run: |
          dotnet --info || true
          which dotnet || true
