name: Reproduce and Resolve setup-dotnet Issue 387

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 2: Using setup-dotnet@v4 to resolve the issue
    - name: Setup .NET 6 with v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Display .NET 6 version with v4
      run: dotnet --version

    - name: Create .NET 6 project with v4
      run: dotnet new console -n TestProject6_v4

    - name: Restore dependencies for .NET 6 with v4
      run: dotnet restore TestProject6_v4

    - name: Build with .NET 6 with v4
      run: dotnet build TestProject6_v4 --no-restore

    - name: Test with .NET 6 with v4
      run: dotnet test TestProject6_v4 --no-build --verbosity normal

    - name: Setup .NET 7 with v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Display .NET 7 version with v4
      run: dotnet --version

    - name: Create .NET 7 project with v4
      run: dotnet new console -n TestProject7_v4

    - name: Restore dependencies for .NET 7 with v4
      run: dotnet restore TestProject7_v4

    - name: Build with .NET 7 with v4
      run: dotnet build TestProject7_v4 --no-restore

    - name: Test with .NET 7 with v4
      run: dotnet test TestProject7_v4 --no-build --verbosity normal
